services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: dining_redis
    restart: always
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: dining_minio
    restart: always
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_PUBLIC_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_HOST_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - minio_data:/data

  app:
    build: .
    container_name: express_app
    restart: always
    ports:
      - "${APP_HOST_PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules

  worker:
    build: .
    container_name: dining_worker
    restart: always
    command: ["npx", "nodemon", "--watch", "src", "--ext", "ts,json", "--exec", "npx tsc && node dist/worker.js", "--legacy-watch"]
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules

  phpmyadmin:
    image: phpmyadmin:5
    container_name: mysql_phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    env_file:
      - .env
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: 64M
    depends_on:
      - db

volumes:
  db_data:
  redis_data:
  minio_data:
  app_node_modules:
