version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: phongan_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: express_app
    restart: always
    ports:
      - "3002:3002"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: dbuser
      DB_PASS: dbpassword
      DB_NAME: phongan_db
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
